# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs: 
  build:
    docker:
      - image: vicarahq/segger-embedded-studio:5.30
    steps: 
      - checkout
      - run:
          name: Build
          command: /ses/bin/emBuild --config "Arm Debug" --project "ci_test" ci_test.emProject

# Orchestrate or schedule a set of jobs

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - build
