name: Build full Segger environment

on: 
  push:
    branches: [ actions_build_container ] # shouldn't be able to push directly to default branch
  pull_request:
    branches: [ actions_build_container ] # And develop

  # Allows running workflow manually from Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ses_build
  SES_VERSION: 5.42.0

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
      
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull base image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker pull ghcr.io/timconnelly/ses_build:latest 
          docker tag ghcr.io/timconnelly/ses_build:latest ses_build
          docker build --target=ses_full --cache-from=ghcr.io/timconnelly/ses_build --cache-to=type=local,dest=/tmp/.buildx-cache-new -t ses_full --load .
          docker images
          docker run --rm -i ses_full bash -c "/opt/ses/bin/emBuild -help"

      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
